// Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "admin@todowinn.com",
    "password": "strongpassword"
}

###
// Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "jun@todowinn.com",
    "password": "strongpassword"
}

###
// Logout endpoint
POST http://localhost:3001/api/auth/logout