// Login

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "admin@todowinn.com",
    "password": "strongpassword"
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "laxy@gmail.com",
    "password": "newpassword"
}