// Get all members
GET http://localhost:3001/api/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoidGVzdHVzZXIxQGdtYWlsLmNvbSIsImlhdCI6MTc1NzA2MjMwOH0.K3ViZjK3Uo0ryKjd6yCcoNPPTFaCQyX-gasDOLt3Ll0

###
// Create member
POST http://localhost:3001/api/members/
Content-Type: application/json

{
    "email": "leah@gmail.com",
    "password": "Honeybunch1"
}

###
// Update member
PATCH http://localhost:3001/api/members/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoibGF4eUBnbWFpbC5jb20iLCJpYXQiOjE3NTcyMDg0NDF9.TF3lqRS5G4fr3Bekl5_6p0ltvGCDh5fnADqxbAelkB4

{
    "password": "newpassword1"
}