GET http://localhost:3001/

###
# Get all projects
GET http://localhost:3001/projects

###
# Get specific project
GET http://localhost:3001/projects/22

###
# Create new project
POST http://localhost:3001/projects/
Content-Type: application/json

{
    "name" : "Disdrive Distracted Driving Detection",
    "dateCreated" : "2025-08-05"
}

###
# Update project
PATCH http://localhost:3001/projects/3
Content-Type: application/json

{
    "name" : "Nicole Nextjss Portfolio",
    "dateCreated" : "2025-08-31"
}

###
# Delete project
DELETE http://localhost:3001/projects/2