GET http://localhost:3001/api

###
# Get all projects
GET http://localhost:3001/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdG9kb3dpbm4uY29tIiwiaWF0IjoxNzU3MTU1NDA4fQ.8h7grDTplVe-J2sXBB9hCO4KQSMP9ZDCmZ13pY0cY8E

###
# Create new project
// jun@gmail.com
POST http://localhost:3001/api/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdG9kb3dpbm4uY29tIiwiaWF0IjoxNzU3MTU1NDA4fQ.8h7grDTplVe-J2sXBB9hCO4KQSMP9ZDCmZ13pY0cY8E

{
    "name" : "Todowinn Project",
    "description" : "testing",
    "dateTarget" : "2025-09-10"
}

###
# Update project
// jun@gmail.com
PATCH http://localhost:3001/api/projects/45
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdG9kb3dpbm4uY29tIiwiaWF0IjoxNzU3MjA2ODYwfQ.2IOAtEA_1bEJRUIihRkH-555_lweTDwURZ_HTCDhR4Y

{
    "status": "FINISHED"
}

###
# Delete project
DELETE http://localhost:3001/api/projects/13